### ISSUE TITLE
upload simplesimb to pypi

### ISSUE THREAD

**Issue by gregordecristoforo** [mwiesenberger/simplesimdb#1]
Hi,
Would it be possible to upload simplesimdb to pypi? At UiT we are currently working on a small library which enables collecting output data from a FELTOR simulation into an xarray dataset ([xFELTOR](https://github.com/uit-cosmo/xFELTOR), inspired by [xBOUT](https://github.com/boutproject/xBOUT)). It would be very useful if simplesimdb could be installed through the setup.py file of xELTOR.

**Comment by mwiesenberger** [comment]
Hi Gregor,
yes totally, it is on my todo list in fact, the reason it isn't there yet was that I wanted to wait a bit until all the initial bugs are ironed out but it seems that we can go ahead now.

**Comment by mwiesenberger** [comment]
Is that even something I need to do? If you have experience could you upload it?

**Comment by gregordecristoforo** [comment]
You just need a pypi account, its straight forward. But if you wish I can do that too.

BTW, I would restructure the code a little bit to follow some packaging conventions (adding a __init__.py file, putting each class in a separate file in a simplesimdb directlry). Shall I create a pull request and upload it to pypi if you approve it?

**Comment by mwiesenberger** [comment]
Hi, I just uploaded it to pypi. 

The package is also a module rather than a package, which if I remember correctly was an important distinction for how to structure the code. I fiddled quite a bit with the package concept and I personally found the module approach with everything in just a single file resonates more with the simplistic approach in this project

**Comment by gregordecristoforo** [comment]
I see, thanks for uploading it! Markus and I were talking about making xFELTOR compatible with simplesimdb which now should be straight forward.
